# Generated by Django 3.1.5 on 2021-01-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
