# Generated by Django 3.1.6 on 2021-02-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210131_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='doc',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.documento'),
            preserve_default=False,
        ),
    ]
