# Generated by Django 3.1.6 on 2021-02-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20210209_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='doc',
            new_name='documento',
        ),
    ]
