# Generated by Django 3.1.6 on 2021-02-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20210209_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='num_doc',
        ),
        migrations.AddField(
            model_name='documento',
            name='num_documento',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
